### ISSUE TITLE
edge.activity.windows.com

### ISSUE THREAD

**Issue by gyCfjSnO** [crazy-max/WindowsSpyBlocker#382] opened 2021-10-02 13:51 UTC
Any Edge browser on my network is unable to sync settings such as favourites, browser settings, autofill data, and passwords.

This is happening because the domain `edge.activity.windows.com` is blocked on the list `https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt`

When whitelisting the domain sync function returns to normal on Edge browser. I confirm this by visiting `edge://sync-internals` and seeing that the Fetch Result	 code is SUCCESS and the Server URL is populated with the domain which was previously blocked before whitelisting.

Blocking is done by AdGuard Home running on Pi4 for anyone curious and DNS hijack performed by router so all DNS queries are sent to AdGuard Home.

I did search and find a duplicate discussion on this matter but it was locked and doesn't look like it was ever resolved ref to #339.

### Screenshot of blocked query

![Screenshot_20211002-234740](https://user-images.githubusercontent.com/49738152/135719180-e18dcff4-095d-4bbe-a7bb-84cc212776e2.png)

**Comment by RavenMacDaddy** [comment] 2021-12-04 18:47
I can confirm this is a real issue.

Checking the sync internals in the Microsoft Edge browser, the full URL seems to be https://edge.activity.windows.com/v1/feeds/me/syncEntities

The current rules makes syncing in the browser completely non-functional.

**Comment by DigitalNXZ** [comment] 2022-02-28 01:58
could be related to the problems I have currently~ disabled, sync works, enabled, sync doesn't work anymore, same with share tabs to other devices

**Comment by crazy-max** [comment] 2022-05-16 12:24
Should be fixed with latest release: https://github.com/crazy-max/WindowsSpyBlocker/releases/tag/4.39.0

**Closed by crazy-max** 2022-05-16 12:24 UTC
Labels: :vertical_traffic_light: rules
