### ISSUE TITLE
data/firewall/win10/spy.txt: Windows Store cannot download apps

### ISSUE THREAD

**Issue by miltador** [crazy-max/WindowsSpyBlocker#15] opened 2016-06-15 04:05 UTC
#### Steps to reproduce this issue
1. Apply hosts from hosts/win10/spy.txt.
2. Launch Windows Store.
3. Try to install any app.
#### Expected Behaviour

Apps should be successfully downloaded and installed.
#### Actual Behaviour

Error: Try the download again.
#### Configuration

**Country** : Ukraine

**Operating system** : Windows 10 Pro 64 bits

**Winver screenshot** : 
![capturewinver](https://cloud.githubusercontent.com/assets/17062283/16067676/6dbdb7fe-32c7-11e6-9b84-64e89d996fbd.PNG)

**Comment by crazy-max** [comment] 2016-06-18 15:41
Can you remove the IPs range `131.253.61.0-131.253.61.255` in `data/firewall/win10/spy.txt` and try again ?

**Comment by crazy-max** [comment] 2016-06-18 18:59
Solved on 3.3.1

**Comment by Gittyperson** [comment] 2017-05-20 21:16
It is happening again. Caused by something in data/firewall/win10/spy.txt. Confirmed several times by enabling/disabling rules in my Firewall. When enabled, Apps fail to install.

**Comment by crazy-max** [comment] 2017-05-27 13:26
@Gittyperson You cannot log to Windows Store or download apps ?

**Comment by Gittyperson** [comment] 2017-05-27 14:31
Log in works fine, app download/install fails (try again later, something happened on our end). Works immediately when disabling the firewall rules. I think a few other services might be affected, like the Optional Features section (speech language downloads etc.), but can't test it now.

**Comment by crazy-max** [comment] 2017-05-27 14:35
Ok thanks

**Comment by crazy-max** [comment] 2017-05-27 14:55
This comes from the ip range `64.4.54.0-64.4.54.255`.
The domain involved is `fe3.delivery.mp.microsoft.com`.
Will be solved on the next release.

**Comment by crazy-max** [comment] 2017-05-27 15:30
Fixed in the latest release 4.2.1

**Comment by Gittyperson** [comment] 2017-05-29 11:23
Thank you, the App installation issue is solved but now there are problems with Windows Update. When I manually check for updates in Settings (don't know if the automatic/background check works differently) I almost always get: "We couldn't connect to the update service. We'll try again later... etc.". Again, disabling the rules makes it work again ("Your device is up to date. Last checked: Today...").

**Comment by crazy-max** [comment] 2017-05-29 11:38
Oh crap, can you open a new issue for that?

**Comment by crazy-max** [comment] 2017-05-30 07:49
@Gittyperson Can you open a new issue for the update service plz ?

**Comment by Gittyperson** [comment] 2017-05-30 23:32
This issue just re-appeared unfortunately.

**Comment by crazy-max** [comment] 2017-05-31 09:03
Yes indeed

**Comment by crazy-max** [comment] 2017-05-31 09:24
Fixed in the latest release 4.3.1

**Comment by Gittyperson** [comment] 2017-05-31 21:19
The issue comes and goes unfortunately. Happening again now, I had to disable the rules to install apps (currently in Greece).

**Comment by crazy-max** [comment] 2017-06-01 09:00
Ok, can you remove these IPs and tell me if it work ?

* 40.113.8.255
* 51.141.32.51
* 52.187.60.107
* 207.46.7.252
* 207.46.101.29
* 207.46.153.155
* 207.46.194.40

**Comment by crazy-max** [comment] 2017-06-01 09:44
Can you try the latest release (4.4.1) ?

**Comment by Gittyperson** [comment] 2017-06-01 15:35
Still fails unfortunately.

**Comment by crazy-max** [comment] 2017-06-02 23:18
@Gittyperson Gotcha! Will be availabe in the next release!

**Comment by crazy-max** [comment] 2017-06-02 23:53
Must be solved with 4.5.1 release

**Closed by crazy-max** 2017-06-02 23:53 UTC
Labels: investigate

**Comment by Gittyperson** [comment] 2017-06-25 15:33
Issue appears again.
